// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4dj8lYa_JHjcUeypl7ai-RzMe_YrsACk',
    appId: '1:777668439356:web:13cdd1947067610949c239',
    messagingSenderId: '777668439356',
    projectId: 'closetai-pbl',
    authDomain: 'closetai-pbl.firebaseapp.com',
    storageBucket: 'closetai-pbl.firebasestorage.app',
    measurementId: 'G-CNJ3PSNJBP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZtKHo4FCml9Bw_BjFtQ9V6ZmlVSGkzwc',
    appId: '1:777668439356:android:00540650f8ca0f7749c239',
    messagingSenderId: '777668439356',
    projectId: 'closetai-pbl',
    storageBucket: 'closetai-pbl.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMQINjYE-nSJvu8t4mhqU-adIPZoPHVk8',
    appId: '1:777668439356:ios:fcb75fbc49c0fbba49c239',
    messagingSenderId: '777668439356',
    projectId: 'closetai-pbl',
    storageBucket: 'closetai-pbl.firebasestorage.app',
    androidClientId: '777668439356-n1nodka6svlpd53bm6d1uj2385mghhol.apps.googleusercontent.com',
    iosClientId: '777668439356-f27p8ot72m2krs86dcss9t9o5nsivm9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.closetAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMQINjYE-nSJvu8t4mhqU-adIPZoPHVk8',
    appId: '1:777668439356:ios:fcb75fbc49c0fbba49c239',
    messagingSenderId: '777668439356',
    projectId: 'closetai-pbl',
    storageBucket: 'closetai-pbl.firebasestorage.app',
    androidClientId: '777668439356-n1nodka6svlpd53bm6d1uj2385mghhol.apps.googleusercontent.com',
    iosClientId: '777668439356-f27p8ot72m2krs86dcss9t9o5nsivm9f.apps.googleusercontent.com',
    iosBundleId: 'com.example.closetAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4dj8lYa_JHjcUeypl7ai-RzMe_YrsACk',
    appId: '1:777668439356:web:65896f63c691b43249c239',
    messagingSenderId: '777668439356',
    projectId: 'closetai-pbl',
    authDomain: 'closetai-pbl.firebaseapp.com',
    storageBucket: 'closetai-pbl.firebasestorage.app',
    measurementId: 'G-Q469M3Z5XF',
  );

}